# Generated by Django 4.1.5 on 2023-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_manufacturer_manufacturer_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_handle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
