# Generated by Django 4.1.5 on 2023-01-11 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
