# Generated by Django 4.1.5 on 2023-01-11 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_modified_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
