# Generated by Django 4.1.5 on 2023-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='dfsd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
