# Generated by Django 4.1.5 on 2023-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_order_category_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
    ]
