# Generated by Django 4.1.5 on 2023-01-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_payment_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='lul', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
