# Generated by Django 4.1.5 on 2023-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
