# Generated by Django 4.1.5 on 2023-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_handle_category_category_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
